spring.application.name=RateLimiterDemo

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

# Rate Limit Configuration
rate.limit.requests=10
rate.limit.window.minutes=1
